//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 05:03:30 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://github.com/ArpadVS/XML_tim14_2019-Publication", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package publications.model.review;
