//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.04 at 04:07:47 AM CEST 
//


package publications.model.letter;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Paragraphs" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="Thanksgiving" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Closure" type="{https://github.com/ArpadVS/XML_tim14_2019-Publication}TClosure"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TBody", propOrder = {
    "paragraphs",
    "thanksgiving",
    "closure"
})
public class TBody {

    @XmlElement(name = "Paragraphs", required = true)
    protected List<String> paragraphs;
    @XmlElement(name = "Thanksgiving", required = true)
    protected String thanksgiving;
    @XmlElement(name = "Closure", required = true)
    protected TClosure closure;

    /**
     * Gets the value of the paragraphs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paragraphs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParagraphs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getParagraphs() {
        if (paragraphs == null) {
            paragraphs = new ArrayList<String>();
        }
        return this.paragraphs;
    }

    /**
     * Gets the value of the thanksgiving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThanksgiving() {
        return thanksgiving;
    }

    /**
     * Sets the value of the thanksgiving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThanksgiving(String value) {
        this.thanksgiving = value;
    }

    /**
     * Gets the value of the closure property.
     * 
     * @return
     *     possible object is
     *     {@link TClosure }
     *     
     */
    public TClosure getClosure() {
        return closure;
    }

    /**
     * Sets the value of the closure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TClosure }
     *     
     */
    public void setClosure(TClosure value) {
        this.closure = value;
    }

}
